// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWoktO_IQqtaIzdq3HrQnw1o1XML1YQ-4',
    appId: '1:787315355035:web:5a71e7eadae4aa5f72853e',
    messagingSenderId: '787315355035',
    projectId: 'aura-drones-ia',
    authDomain: 'aura-drones-ia.firebaseapp.com',
    storageBucket: 'aura-drones-ia.firebasestorage.app',
    measurementId: 'G-DEVMZHHHTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZkaTY-wTEwlLhX5tjxSe_QYabdaqajU',
    appId: '1:787315355035:android:0ece3902f4bd91bd72853e',
    messagingSenderId: '787315355035',
    projectId: 'aura-drones-ia',
    storageBucket: 'aura-drones-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZiP4ztWjuJmpV5MJ-_91duE5Gf-_6sw',
    appId: '1:787315355035:ios:f5db6d0c9fd5623c72853e',
    messagingSenderId: '787315355035',
    projectId: 'aura-drones-ia',
    storageBucket: 'aura-drones-ia.firebasestorage.app',
    iosBundleId: 'com.aurapilot.auraDronesIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZiP4ztWjuJmpV5MJ-_91duE5Gf-_6sw',
    appId: '1:787315355035:ios:f5db6d0c9fd5623c72853e',
    messagingSenderId: '787315355035',
    projectId: 'aura-drones-ia',
    storageBucket: 'aura-drones-ia.firebasestorage.app',
    iosBundleId: 'com.aurapilot.auraDronesIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWoktO_IQqtaIzdq3HrQnw1o1XML1YQ-4',
    appId: '1:787315355035:web:512014b2e197882872853e',
    messagingSenderId: '787315355035',
    projectId: 'aura-drones-ia',
    authDomain: 'aura-drones-ia.firebaseapp.com',
    storageBucket: 'aura-drones-ia.firebasestorage.app',
    measurementId: 'G-9GNPXCQG47',
  );
}
